// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUp2s744x7YbJxRHB3rhl4OKtHJ_4jBUU',
    appId: '1:542404511721:web:79bfb7ac497ddf0b652d78',
    messagingSenderId: '542404511721',
    projectId: 'worldcup22db',
    authDomain: 'worldcup22db.firebaseapp.com',
    storageBucket: 'worldcup22db.appspot.com',
    measurementId: 'G-Y7YFZN1TQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx15Aq4-vIAOMMFC5tZutEXsluYO5fG8M',
    appId: '1:542404511721:android:7b77ea6f8a4c1b02652d78',
    messagingSenderId: '542404511721',
    projectId: 'worldcup22db',
    storageBucket: 'worldcup22db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzn5sqv-GWyF8QaHjYbAJFjaYUi-lGc7U',
    appId: '1:542404511721:ios:1dd40c3d064dc5a8652d78',
    messagingSenderId: '542404511721',
    projectId: 'worldcup22db',
    storageBucket: 'worldcup22db.appspot.com',
    iosClientId: '542404511721-bc4kipt64275hophhdc0jt6d3pd4lsc2.apps.googleusercontent.com',
    iosBundleId: 'com.example.worldcup22db',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzn5sqv-GWyF8QaHjYbAJFjaYUi-lGc7U',
    appId: '1:542404511721:ios:1dd40c3d064dc5a8652d78',
    messagingSenderId: '542404511721',
    projectId: 'worldcup22db',
    storageBucket: 'worldcup22db.appspot.com',
    iosClientId: '542404511721-bc4kipt64275hophhdc0jt6d3pd4lsc2.apps.googleusercontent.com',
    iosBundleId: 'com.example.worldcup22db',
  );
}
